ALTER TABLE "PlanetCell"
ADD COLUMN "dominantPlantKey" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN "dominantPlantName" TEXT NOT NULL DEFAULT 'No Established Plant Life',
ADD COLUMN "plantSuitabilityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "plantDensity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "biomassScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ediblePlantScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "woodMaterialScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "medicinalPotentialScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "biodiversityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "regrowthRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "seasonalStressScore" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "plantTags" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "plantGeneratedAt" TIMESTAMP(3),
ADD COLUMN "plantUpdatedAt" TIMESTAMP(3);

CREATE INDEX "PlanetCell_planetId_dominantPlantKey_idx" ON "PlanetCell"("planetId", "dominantPlantKey");
