ALTER TABLE "PlanetCell"
ADD COLUMN "plantConsumptionRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "effectivePlantBiomass" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "predationPressure" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "predatorPreyBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "foodStability" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "carryingCapacityUsage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "migrationActivity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "populationGrowthRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ecosystemHealthScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ecosystemHealthStatus" TEXT NOT NULL DEFAULT 'Collapsed',
ADD COLUMN "ecosystemEvents" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "ecosystemHistory" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "movementVectors" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "AnimalPopulation"
ADD COLUMN "predationPressure" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "competitionPressure" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "carryingCapacityUsage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "inboundMigration" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "outboundMigration" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "netMigration" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "populationTrend" DOUBLE PRECISION NOT NULL DEFAULT 0;

CREATE INDEX "PlanetCell_planetId_ecosystemHealthStatus_idx" ON "PlanetCell"("planetId", "ecosystemHealthStatus");
