import type { BiomeKey } from "./biome-definitions";

export const ANIMAL_GUILD_KEYS = [
  "aquatic-microfauna",
  "fish",
  "amphibians",
  "insects",
  "small-herbivores",
  "large-herbivores",
  "browsers",
  "grazers",
  "small-predators",
  "apex-predators",
  "scavengers",
  "birds",
  "reptiles",
  "burrowers",
  "cold-adapted-animals",
  "desert-adapted-animals",
  "wetland-animals",
] as const;

export type AnimalGuildKey = (typeof ANIMAL_GUILD_KEYS)[number];

export type AnimalCategory =
  | "aquatic"
  | "amphibian"
  | "invertebrate"
  | "herbivore"
  | "predator"
  | "scavenger"
  | "aerial"
  | "reptile"
  | "burrower"
  | "specialist";

export type AnimalRange = readonly [number, number];

export type AnimalGuildDefinition = {
  readonly key: AnimalGuildKey;
  readonly displayName: string;
  readonly category: AnimalCategory;
  readonly color: string;
  readonly biomePreferences: readonly BiomeKey[];
  readonly plantFoodDependency: number;
  readonly preyDependency: number;
  readonly waterDependency: number;
  readonly temperatureRangeC: AnimalRange;
  readonly precipitationRange: AnimalRange;
  readonly elevationTolerance: AnimalRange;
  readonly shelterRequirement: number;
  readonly reproductionRate: number;
  readonly mobilityScore: number;
  readonly migrationTendency: number;
  readonly humanFoodValue: number;
  readonly dangerScore: number;
  readonly biodiversityValue: number;
  readonly tags: readonly string[];
};

function defineGuild(definition: AnimalGuildDefinition): AnimalGuildDefinition {
  return Object.freeze(definition);
}

export const ANIMAL_GUILD_DEFINITIONS: Record<AnimalGuildKey, AnimalGuildDefinition> = Object.freeze({
  "aquatic-microfauna": defineGuild({
    key: "aquatic-microfauna",
    displayName: "Aquatic Microfauna",
    category: "aquatic",
    color: "#58b7a0",
    biomePreferences: Object.freeze(["ocean", "coast", "lake", "river-wetland", "swamp-marsh"]),
    plantFoodDependency: 0.34,
    preyDependency: 0.02,
    waterDependency: 0.95,
    temperatureRangeC: [-3, 34],
    precipitationRange: [0, 1],
    elevationTolerance: [0, 0.82],
    shelterRequirement: 0.04,
    reproductionRate: 0.95,
    mobilityScore: 0.32,
    migrationTendency: 0.18,
    humanFoodValue: 0.12,
    dangerScore: 0.01,
    biodiversityValue: 0.62,
    tags: Object.freeze(["aquatic", "microfauna", "plankton", "food-chain-base", "fast-reproduction"]),
  }),
  fish: defineGuild({
    key: "fish",
    displayName: "Fish",
    category: "aquatic",
    color: "#2f91c8",
    biomePreferences: Object.freeze(["ocean", "coast", "lake", "river-wetland"]),
    plantFoodDependency: 0.22,
    preyDependency: 0.24,
    waterDependency: 0.92,
    temperatureRangeC: [-2, 32],
    precipitationRange: [0, 1],
    elevationTolerance: [0, 0.82],
    shelterRequirement: 0.18,
    reproductionRate: 0.62,
    mobilityScore: 0.62,
    migrationTendency: 0.46,
    humanFoodValue: 0.86,
    dangerScore: 0.06,
    biodiversityValue: 0.56,
    tags: Object.freeze(["aquatic", "fishery", "protein", "migration", "freshwater"]),
  }),
  amphibians: defineGuild({
    key: "amphibians",
    displayName: "Amphibians",
    category: "amphibian",
    color: "#74a85c",
    biomePreferences: Object.freeze(["river-wetland", "swamp-marsh", "lake", "temperate-forest", "tropical-rainforest"]),
    plantFoodDependency: 0.2,
    preyDependency: 0.28,
    waterDependency: 0.78,
    temperatureRangeC: [4, 32],
    precipitationRange: [0.42, 1],
    elevationTolerance: [0.28, 0.72],
    shelterRequirement: 0.38,
    reproductionRate: 0.68,
    mobilityScore: 0.28,
    migrationTendency: 0.18,
    humanFoodValue: 0.22,
    dangerScore: 0.08,
    biodiversityValue: 0.64,
    tags: Object.freeze(["amphibian", "wetland", "insect-control", "moisture-sensitive", "indicator-species"]),
  }),
  insects: defineGuild({
    key: "insects",
    displayName: "Insects",
    category: "invertebrate",
    color: "#c6a34a",
    biomePreferences: Object.freeze(["tropical-rainforest", "tropical-seasonal-forest", "swamp-marsh", "temperate-forest", "savanna", "river-wetland"]),
    plantFoodDependency: 0.46,
    preyDependency: 0.04,
    waterDependency: 0.26,
    temperatureRangeC: [4, 38],
    precipitationRange: [0.12, 1],
    elevationTolerance: [0.22, 0.84],
    shelterRequirement: 0.18,
    reproductionRate: 0.92,
    mobilityScore: 0.42,
    migrationTendency: 0.22,
    humanFoodValue: 0.2,
    dangerScore: 0.18,
    biodiversityValue: 0.88,
    tags: Object.freeze(["insect", "pollinator", "decomposer", "prey-base", "disease-vector"]),
  }),
  "small-herbivores": defineGuild({
    key: "small-herbivores",
    displayName: "Small Herbivores",
    category: "herbivore",
    color: "#aeb861",
    biomePreferences: Object.freeze(["temperate-grassland", "temperate-forest", "mediterranean-shrubland", "savanna", "boreal-forest", "tundra"]),
    plantFoodDependency: 0.72,
    preyDependency: 0,
    waterDependency: 0.32,
    temperatureRangeC: [-12, 32],
    precipitationRange: [0.08, 0.84],
    elevationTolerance: [0.28, 0.86],
    shelterRequirement: 0.28,
    reproductionRate: 0.76,
    mobilityScore: 0.5,
    migrationTendency: 0.24,
    humanFoodValue: 0.48,
    dangerScore: 0.03,
    biodiversityValue: 0.38,
    tags: Object.freeze(["herbivore", "small-game", "prey", "forage", "fast-reproduction"]),
  }),
  "large-herbivores": defineGuild({
    key: "large-herbivores",
    displayName: "Large Herbivores",
    category: "herbivore",
    color: "#8d9a48",
    biomePreferences: Object.freeze(["savanna", "temperate-grassland", "temperate-forest", "tropical-seasonal-forest", "boreal-forest"]),
    plantFoodDependency: 0.82,
    preyDependency: 0,
    waterDependency: 0.46,
    temperatureRangeC: [-8, 34],
    precipitationRange: [0.16, 0.82],
    elevationTolerance: [0.32, 0.76],
    shelterRequirement: 0.22,
    reproductionRate: 0.34,
    mobilityScore: 0.72,
    migrationTendency: 0.54,
    humanFoodValue: 0.92,
    dangerScore: 0.24,
    biodiversityValue: 0.42,
    tags: Object.freeze(["herbivore", "large-game", "prey", "migration", "meat"]),
  }),
  browsers: defineGuild({
    key: "browsers",
    displayName: "Browsers",
    category: "herbivore",
    color: "#7c944f",
    biomePreferences: Object.freeze(["temperate-forest", "tropical-seasonal-forest", "mediterranean-shrubland", "savanna", "boreal-forest"]),
    plantFoodDependency: 0.68,
    preyDependency: 0,
    waterDependency: 0.36,
    temperatureRangeC: [-10, 34],
    precipitationRange: [0.18, 0.9],
    elevationTolerance: [0.3, 0.82],
    shelterRequirement: 0.34,
    reproductionRate: 0.44,
    mobilityScore: 0.58,
    migrationTendency: 0.32,
    humanFoodValue: 0.72,
    dangerScore: 0.12,
    biodiversityValue: 0.42,
    tags: Object.freeze(["herbivore", "browse", "forest-edge", "meat", "prey"]),
  }),
  grazers: defineGuild({
    key: "grazers",
    displayName: "Grazers",
    category: "herbivore",
    color: "#b5b84e",
    biomePreferences: Object.freeze(["temperate-grassland", "savanna", "tundra", "river-wetland"]),
    plantFoodDependency: 0.86,
    preyDependency: 0,
    waterDependency: 0.38,
    temperatureRangeC: [-14, 36],
    precipitationRange: [0.12, 0.68],
    elevationTolerance: [0.28, 0.78],
    shelterRequirement: 0.12,
    reproductionRate: 0.48,
    mobilityScore: 0.76,
    migrationTendency: 0.64,
    humanFoodValue: 0.88,
    dangerScore: 0.14,
    biodiversityValue: 0.4,
    tags: Object.freeze(["herbivore", "grazer", "grassland", "migration", "domestication-candidate"]),
  }),
  "small-predators": defineGuild({
    key: "small-predators",
    displayName: "Small Predators",
    category: "predator",
    color: "#9b5b45",
    biomePreferences: Object.freeze(["temperate-forest", "temperate-grassland", "savanna", "boreal-forest", "tropical-seasonal-forest", "tundra"]),
    plantFoodDependency: 0.08,
    preyDependency: 0.56,
    waterDependency: 0.24,
    temperatureRangeC: [-18, 36],
    precipitationRange: [0.08, 0.92],
    elevationTolerance: [0.28, 0.9],
    shelterRequirement: 0.32,
    reproductionRate: 0.46,
    mobilityScore: 0.62,
    migrationTendency: 0.28,
    humanFoodValue: 0.18,
    dangerScore: 0.28,
    biodiversityValue: 0.44,
    tags: Object.freeze(["predator", "mesopredator", "prey-control", "fur", "territorial"]),
  }),
  "apex-predators": defineGuild({
    key: "apex-predators",
    displayName: "Apex Predators",
    category: "predator",
    color: "#7f3d38",
    biomePreferences: Object.freeze(["savanna", "temperate-forest", "tropical-rainforest", "boreal-forest", "tropical-seasonal-forest"]),
    plantFoodDependency: 0.02,
    preyDependency: 0.84,
    waterDependency: 0.34,
    temperatureRangeC: [-16, 36],
    precipitationRange: [0.12, 1],
    elevationTolerance: [0.24, 0.86],
    shelterRequirement: 0.42,
    reproductionRate: 0.18,
    mobilityScore: 0.78,
    migrationTendency: 0.34,
    humanFoodValue: 0.1,
    dangerScore: 0.92,
    biodiversityValue: 0.58,
    tags: Object.freeze(["predator", "apex", "danger", "territorial", "keystone"]),
  }),
  scavengers: defineGuild({
    key: "scavengers",
    displayName: "Scavengers",
    category: "scavenger",
    color: "#8e7054",
    biomePreferences: Object.freeze(["savanna", "desert", "badlands-rocky", "temperate-grassland", "coast", "tundra"]),
    plantFoodDependency: 0.06,
    preyDependency: 0.42,
    waterDependency: 0.18,
    temperatureRangeC: [-16, 42],
    precipitationRange: [0, 0.9],
    elevationTolerance: [0.2, 0.88],
    shelterRequirement: 0.14,
    reproductionRate: 0.38,
    mobilityScore: 0.74,
    migrationTendency: 0.38,
    humanFoodValue: 0.08,
    dangerScore: 0.22,
    biodiversityValue: 0.36,
    tags: Object.freeze(["scavenger", "carrion", "cleanup", "wide-ranging", "disease-risk"]),
  }),
  birds: defineGuild({
    key: "birds",
    displayName: "Birds",
    category: "aerial",
    color: "#88a9bf",
    biomePreferences: Object.freeze(["coast", "lake", "river-wetland", "swamp-marsh", "temperate-forest", "tropical-rainforest", "savanna"]),
    plantFoodDependency: 0.26,
    preyDependency: 0.22,
    waterDependency: 0.28,
    temperatureRangeC: [-12, 36],
    precipitationRange: [0.1, 1],
    elevationTolerance: [0.12, 0.9],
    shelterRequirement: 0.28,
    reproductionRate: 0.42,
    mobilityScore: 0.92,
    migrationTendency: 0.72,
    humanFoodValue: 0.42,
    dangerScore: 0.08,
    biodiversityValue: 0.66,
    tags: Object.freeze(["bird", "aerial", "migration", "eggs", "seed-dispersal"]),
  }),
  reptiles: defineGuild({
    key: "reptiles",
    displayName: "Reptiles",
    category: "reptile",
    color: "#7f9b4b",
    biomePreferences: Object.freeze(["desert", "savanna", "mediterranean-shrubland", "tropical-seasonal-forest", "swamp-marsh", "coast"]),
    plantFoodDependency: 0.12,
    preyDependency: 0.34,
    waterDependency: 0.18,
    temperatureRangeC: [10, 42],
    precipitationRange: [0, 0.82],
    elevationTolerance: [0.22, 0.82],
    shelterRequirement: 0.24,
    reproductionRate: 0.38,
    mobilityScore: 0.42,
    migrationTendency: 0.12,
    humanFoodValue: 0.34,
    dangerScore: 0.34,
    biodiversityValue: 0.44,
    tags: Object.freeze(["reptile", "warm-adapted", "burrow", "ambush", "eggs"]),
  }),
  burrowers: defineGuild({
    key: "burrowers",
    displayName: "Burrowers",
    category: "burrower",
    color: "#a47752",
    biomePreferences: Object.freeze(["temperate-grassland", "desert", "badlands-rocky", "mediterranean-shrubland", "savanna", "tundra"]),
    plantFoodDependency: 0.44,
    preyDependency: 0.1,
    waterDependency: 0.18,
    temperatureRangeC: [-12, 40],
    precipitationRange: [0.02, 0.68],
    elevationTolerance: [0.28, 0.86],
    shelterRequirement: 0.08,
    reproductionRate: 0.64,
    mobilityScore: 0.28,
    migrationTendency: 0.08,
    humanFoodValue: 0.38,
    dangerScore: 0.05,
    biodiversityValue: 0.32,
    tags: Object.freeze(["burrower", "small-game", "soil-turnover", "shelter", "prey"]),
  }),
  "cold-adapted-animals": defineGuild({
    key: "cold-adapted-animals",
    displayName: "Cold-adapted Animals",
    category: "specialist",
    color: "#c8d7d8",
    biomePreferences: Object.freeze(["tundra", "boreal-forest", "ice-sheet", "alpine-mountain"]),
    plantFoodDependency: 0.38,
    preyDependency: 0.18,
    waterDependency: 0.24,
    temperatureRangeC: [-36, 8],
    precipitationRange: [0.02, 0.72],
    elevationTolerance: [0.34, 1],
    shelterRequirement: 0.22,
    reproductionRate: 0.26,
    mobilityScore: 0.68,
    migrationTendency: 0.62,
    humanFoodValue: 0.72,
    dangerScore: 0.22,
    biodiversityValue: 0.28,
    tags: Object.freeze(["cold", "fur", "seasonal-migration", "low-density", "meat"]),
  }),
  "desert-adapted-animals": defineGuild({
    key: "desert-adapted-animals",
    displayName: "Desert-adapted Animals",
    category: "specialist",
    color: "#d2b36b",
    biomePreferences: Object.freeze(["desert", "badlands-rocky", "mediterranean-shrubland"]),
    plantFoodDependency: 0.28,
    preyDependency: 0.16,
    waterDependency: 0.06,
    temperatureRangeC: [2, 45],
    precipitationRange: [0, 0.32],
    elevationTolerance: [0.3, 0.86],
    shelterRequirement: 0.14,
    reproductionRate: 0.32,
    mobilityScore: 0.58,
    migrationTendency: 0.36,
    humanFoodValue: 0.32,
    dangerScore: 0.18,
    biodiversityValue: 0.26,
    tags: Object.freeze(["desert", "water-efficient", "nocturnal", "sparse", "heat-adapted"]),
  }),
  "wetland-animals": defineGuild({
    key: "wetland-animals",
    displayName: "Wetland Animals",
    category: "specialist",
    color: "#4f9a78",
    biomePreferences: Object.freeze(["river-wetland", "swamp-marsh", "lake", "coast"]),
    plantFoodDependency: 0.42,
    preyDependency: 0.24,
    waterDependency: 0.82,
    temperatureRangeC: [0, 34],
    precipitationRange: [0.38, 1],
    elevationTolerance: [0.24, 0.72],
    shelterRequirement: 0.34,
    reproductionRate: 0.54,
    mobilityScore: 0.52,
    migrationTendency: 0.36,
    humanFoodValue: 0.54,
    dangerScore: 0.2,
    biodiversityValue: 0.7,
    tags: Object.freeze(["wetland", "aquatic-edge", "nesting", "high-biodiversity", "water-dependent"]),
  }),
});

export function getAnimalGuildDefinition(key: AnimalGuildKey): AnimalGuildDefinition {
  return ANIMAL_GUILD_DEFINITIONS[key];
}

export function getAnimalGuildDefinitions(): readonly AnimalGuildDefinition[] {
  return ANIMAL_GUILD_KEYS.map((key) => ANIMAL_GUILD_DEFINITIONS[key]);
}
