export const BIOME_KEYS = [
  "ocean",
  "coast",
  "lake",
  "river-wetland",
  "ice-sheet",
  "tundra",
  "boreal-forest",
  "temperate-forest",
  "temperate-grassland",
  "mediterranean-shrubland",
  "desert",
  "savanna",
  "tropical-seasonal-forest",
  "tropical-rainforest",
  "alpine-mountain",
  "volcanic-barren",
  "badlands-rocky",
  "swamp-marsh",
] as const;

export type BiomeKey = (typeof BIOME_KEYS)[number];

export type BiomeCategory =
  | "marine"
  | "freshwater"
  | "polar"
  | "forest"
  | "grassland"
  | "dryland"
  | "tropical"
  | "mountain"
  | "barren"
  | "wetland";

export type PreferenceRange = readonly [number, number];

export type BiomeDefinition = {
  readonly key: BiomeKey;
  readonly displayName: string;
  readonly category: BiomeCategory;
  readonly color: string;
  readonly description: string;
  readonly habitabilityScore: number;
  readonly fertilityScore: number;
  readonly waterAvailabilityScore: number;
  readonly vegetationDensity: number;
  readonly temperaturePreferenceRange: PreferenceRange;
  readonly precipitationPreferenceRange: PreferenceRange;
  readonly elevationPreferenceRange: PreferenceRange;
  readonly tags: readonly string[];
};

function defineBiome(definition: BiomeDefinition): BiomeDefinition {
  return Object.freeze(definition);
}

export const BIOME_DEFINITIONS: Record<BiomeKey, BiomeDefinition> = Object.freeze({
  "ocean": defineBiome({
    key: "ocean",
    displayName: "Ocean",
    category: "marine",
    color: "#1d4f91",
    description: "Open saltwater biome with low direct settlement potential and strong climate influence.",
    habitabilityScore: 0.12,
    fertilityScore: 0.18,
    waterAvailabilityScore: 1,
    vegetationDensity: 0.12,
    temperaturePreferenceRange: [-2, 32],
    precipitationPreferenceRange: [0, 1],
    elevationPreferenceRange: [0, 0.42],
    tags: Object.freeze(["marine", "saltwater", "navigation", "fisheries"]),
  }),
  "coast": defineBiome({
    key: "coast",
    displayName: "Coast",
    category: "marine",
    color: "#2f8aa3",
    description: "Shallow marine and shoreline transition zone with high movement and food potential.",
    habitabilityScore: 0.68,
    fertilityScore: 0.56,
    waterAvailabilityScore: 0.88,
    vegetationDensity: 0.46,
    temperaturePreferenceRange: [-4, 34],
    precipitationPreferenceRange: [0.1, 1],
    elevationPreferenceRange: [0.32, 0.48],
    tags: Object.freeze(["marine", "shore", "fish", "trade"]),
  }),
  "lake": defineBiome({
    key: "lake",
    displayName: "Lake",
    category: "freshwater",
    color: "#367fb6",
    description: "Inland freshwater body or persistent basin lake.",
    habitabilityScore: 0.64,
    fertilityScore: 0.52,
    waterAvailabilityScore: 0.96,
    vegetationDensity: 0.42,
    temperaturePreferenceRange: [-8, 30],
    precipitationPreferenceRange: [0.2, 1],
    elevationPreferenceRange: [0.38, 0.82],
    tags: Object.freeze(["freshwater", "fish", "basin", "settlement-water"]),
  }),
  "river-wetland": defineBiome({
    key: "river-wetland",
    displayName: "River/Wetland",
    category: "wetland",
    color: "#4a9a75",
    description: "River corridor, floodplain, or saturated lowland with reliable freshwater.",
    habitabilityScore: 0.76,
    fertilityScore: 0.82,
    waterAvailabilityScore: 0.94,
    vegetationDensity: 0.74,
    temperaturePreferenceRange: [-4, 34],
    precipitationPreferenceRange: [0.35, 1],
    elevationPreferenceRange: [0.4, 0.72],
    tags: Object.freeze(["freshwater", "river", "wetland", "fertile", "settlement-water"]),
  }),
  "ice-sheet": defineBiome({
    key: "ice-sheet",
    displayName: "Ice Sheet",
    category: "polar",
    color: "#dbeafe",
    description: "Permanent ice cover where biological productivity and settlement options are minimal.",
    habitabilityScore: 0.03,
    fertilityScore: 0.01,
    waterAvailabilityScore: 0.22,
    vegetationDensity: 0.01,
    temperaturePreferenceRange: [-60, -8],
    precipitationPreferenceRange: [0, 0.7],
    elevationPreferenceRange: [0.38, 1],
    tags: Object.freeze(["ice", "polar", "harsh", "glacial"]),
  }),
  "tundra": defineBiome({
    key: "tundra",
    displayName: "Tundra",
    category: "polar",
    color: "#b8bfa3",
    description: "Cold treeless land with short growing seasons and low vegetation.",
    habitabilityScore: 0.24,
    fertilityScore: 0.18,
    waterAvailabilityScore: 0.42,
    vegetationDensity: 0.18,
    temperaturePreferenceRange: [-15, 5],
    precipitationPreferenceRange: [0.05, 0.45],
    elevationPreferenceRange: [0.42, 0.72],
    tags: Object.freeze(["cold", "permafrost", "low-vegetation"]),
  }),
  "boreal-forest": defineBiome({
    key: "boreal-forest",
    displayName: "Boreal Forest",
    category: "forest",
    color: "#426b4b",
    description: "Cold conifer forest sustained by moderate moisture and long winters.",
    habitabilityScore: 0.46,
    fertilityScore: 0.36,
    waterAvailabilityScore: 0.58,
    vegetationDensity: 0.62,
    temperaturePreferenceRange: [-6, 9],
    precipitationPreferenceRange: [0.25, 0.72],
    elevationPreferenceRange: [0.42, 0.74],
    tags: Object.freeze(["forest", "cold", "timber", "conifer"]),
  }),
  "temperate-forest": defineBiome({
    key: "temperate-forest",
    displayName: "Temperate Forest",
    category: "forest",
    color: "#2f7d4f",
    description: "Moist mid-latitude forest with strong fertility and timber potential.",
    habitabilityScore: 0.78,
    fertilityScore: 0.78,
    waterAvailabilityScore: 0.72,
    vegetationDensity: 0.82,
    temperaturePreferenceRange: [5, 22],
    precipitationPreferenceRange: [0.45, 0.9],
    elevationPreferenceRange: [0.42, 0.72],
    tags: Object.freeze(["forest", "temperate", "timber", "fertile"]),
  }),
  "temperate-grassland": defineBiome({
    key: "temperate-grassland",
    displayName: "Temperate Grassland",
    category: "grassland",
    color: "#9cae55",
    description: "Open mid-latitude grassland with seasonal moisture and strong grazing potential.",
    habitabilityScore: 0.72,
    fertilityScore: 0.68,
    waterAvailabilityScore: 0.48,
    vegetationDensity: 0.48,
    temperaturePreferenceRange: [3, 24],
    precipitationPreferenceRange: [0.18, 0.58],
    elevationPreferenceRange: [0.42, 0.7],
    tags: Object.freeze(["grass", "temperate", "grazing", "settlement"]),
  }),
  "mediterranean-shrubland": defineBiome({
    key: "mediterranean-shrubland",
    displayName: "Mediterranean/Shrubland",
    category: "dryland",
    color: "#b19a58",
    description: "Warm seasonal shrubland, often forming transitions between dry grass and forest.",
    habitabilityScore: 0.58,
    fertilityScore: 0.44,
    waterAvailabilityScore: 0.34,
    vegetationDensity: 0.36,
    temperaturePreferenceRange: [10, 28],
    precipitationPreferenceRange: [0.18, 0.48],
    elevationPreferenceRange: [0.42, 0.72],
    tags: Object.freeze(["shrub", "seasonal", "fire-prone", "transition"]),
  }),
  "desert": defineBiome({
    key: "desert",
    displayName: "Desert",
    category: "dryland",
    color: "#d5b56f",
    description: "Arid land with sparse vegetation and severe water limits.",
    habitabilityScore: 0.16,
    fertilityScore: 0.08,
    waterAvailabilityScore: 0.08,
    vegetationDensity: 0.06,
    temperaturePreferenceRange: [8, 45],
    precipitationPreferenceRange: [0, 0.2],
    elevationPreferenceRange: [0.42, 0.78],
    tags: Object.freeze(["arid", "harsh", "low-water", "sparse"]),
  }),
  "savanna": defineBiome({
    key: "savanna",
    displayName: "Savanna",
    category: "tropical",
    color: "#b8b857",
    description: "Warm grassland with scattered trees and strong wet/dry seasonality.",
    habitabilityScore: 0.6,
    fertilityScore: 0.5,
    waterAvailabilityScore: 0.38,
    vegetationDensity: 0.42,
    temperaturePreferenceRange: [20, 34],
    precipitationPreferenceRange: [0.22, 0.58],
    elevationPreferenceRange: [0.42, 0.7],
    tags: Object.freeze(["grass", "tropical", "seasonal", "grazing"]),
  }),
  "tropical-seasonal-forest": defineBiome({
    key: "tropical-seasonal-forest",
    displayName: "Tropical Seasonal Forest",
    category: "tropical",
    color: "#4f8f3a",
    description: "Warm forest with pronounced wet and dry seasons.",
    habitabilityScore: 0.66,
    fertilityScore: 0.62,
    waterAvailabilityScore: 0.58,
    vegetationDensity: 0.72,
    temperaturePreferenceRange: [20, 34],
    precipitationPreferenceRange: [0.48, 0.78],
    elevationPreferenceRange: [0.42, 0.7],
    tags: Object.freeze(["forest", "tropical", "seasonal", "biodiverse"]),
  }),
  "tropical-rainforest": defineBiome({
    key: "tropical-rainforest",
    displayName: "Tropical Rainforest",
    category: "tropical",
    color: "#176d3b",
    description: "Hot, wet, dense forest with the highest biodiversity potential.",
    habitabilityScore: 0.56,
    fertilityScore: 0.7,
    waterAvailabilityScore: 0.88,
    vegetationDensity: 0.98,
    temperaturePreferenceRange: [22, 35],
    precipitationPreferenceRange: [0.72, 1],
    elevationPreferenceRange: [0.42, 0.68],
    tags: Object.freeze(["forest", "tropical", "rainforest", "biodiversity", "dense"]),
  }),
  "alpine-mountain": defineBiome({
    key: "alpine-mountain",
    displayName: "Alpine/Mountain",
    category: "mountain",
    color: "#8f9188",
    description: "High elevation mountain biome with thin soils and cold exposure.",
    habitabilityScore: 0.2,
    fertilityScore: 0.12,
    waterAvailabilityScore: 0.38,
    vegetationDensity: 0.16,
    temperaturePreferenceRange: [-20, 12],
    precipitationPreferenceRange: [0.05, 0.9],
    elevationPreferenceRange: [0.72, 1],
    tags: Object.freeze(["mountain", "cold", "thin-soil", "source-water"]),
  }),
  "volcanic-barren": defineBiome({
    key: "volcanic-barren",
    displayName: "Volcanic/Barren",
    category: "barren",
    color: "#5d5651",
    description: "Recently active or unstable volcanic terrain with little established ecology.",
    habitabilityScore: 0.08,
    fertilityScore: 0.12,
    waterAvailabilityScore: 0.16,
    vegetationDensity: 0.04,
    temperaturePreferenceRange: [-5, 38],
    precipitationPreferenceRange: [0, 0.8],
    elevationPreferenceRange: [0.46, 1],
    tags: Object.freeze(["volcanic", "barren", "unstable", "mineral-rich"]),
  }),
  "badlands-rocky": defineBiome({
    key: "badlands-rocky",
    displayName: "Badlands/Rocky",
    category: "barren",
    color: "#9a785e",
    description: "Eroded rocky terrain with poor soils and limited vegetation.",
    habitabilityScore: 0.18,
    fertilityScore: 0.1,
    waterAvailabilityScore: 0.18,
    vegetationDensity: 0.1,
    temperaturePreferenceRange: [0, 36],
    precipitationPreferenceRange: [0, 0.35],
    elevationPreferenceRange: [0.5, 0.86],
    tags: Object.freeze(["rocky", "eroded", "dry", "poor-soil"]),
  }),
  "swamp-marsh": defineBiome({
    key: "swamp-marsh",
    displayName: "Swamp/Marsh",
    category: "wetland",
    color: "#3d7a5f",
    description: "Saturated lowland with dense wet vegetation and difficult movement.",
    habitabilityScore: 0.46,
    fertilityScore: 0.74,
    waterAvailabilityScore: 0.98,
    vegetationDensity: 0.86,
    temperaturePreferenceRange: [6, 34],
    precipitationPreferenceRange: [0.62, 1],
    elevationPreferenceRange: [0.4, 0.58],
    tags: Object.freeze(["wetland", "freshwater", "marsh", "fertile", "disease-risk"]),
  }),
});

export function getBiomeDefinition(key: BiomeKey): BiomeDefinition {
  return BIOME_DEFINITIONS[key];
}