ALTER TABLE "World"
ADD COLUMN "tickDurationSeconds" DOUBLE PRECISION NOT NULL DEFAULT 60,
ADD COLUMN "dayLengthSeconds" DOUBLE PRECISION NOT NULL DEFAULT 86400,
ADD COLUMN "yearLengthDays" INTEGER NOT NULL DEFAULT 365,
ADD COLUMN "axialTiltDegrees" DOUBLE PRECISION NOT NULL DEFAULT 23.44,
ADD COLUMN "orbitalEccentricity" DOUBLE PRECISION NOT NULL DEFAULT 0.0167,
ADD COLUMN "initialEpochName" TEXT NOT NULL DEFAULT 'First Dawn',
ADD COLUMN "initialYear" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "initialDay" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "initialHour" DOUBLE PRECISION NOT NULL DEFAULT 6;