ALTER TABLE "PlanetCell"
ADD COLUMN "dominantAnimalGuildKey" TEXT NOT NULL DEFAULT 'aquatic-microfauna',
ADD COLUMN "dominantAnimalGuildName" TEXT NOT NULL DEFAULT 'Aquatic Microfauna',
ADD COLUMN "animalSuitabilityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "herbivoreCapacity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "predatorCapacity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "preyAvailability" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "animalDensity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "migrationPressure" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "dangerScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "huntingValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "domesticationPotential" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "animalBiodiversityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "carryingCapacityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "animalTags" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "animalGeneratedAt" TIMESTAMP(3),
ADD COLUMN "animalUpdatedAt" TIMESTAMP(3);

CREATE INDEX "PlanetCell_planetId_dominantAnimalGuildKey_idx" ON "PlanetCell"("planetId", "dominantAnimalGuildKey");